version: "3"
volumes:
  yarn-cache:
services:
  poker:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /workspaces
    volumes:
      - ../:/workspaces
      - yarn-cache:/usr/local/share/.cache/yarn/v6
      - ${HOME}${USERPROFILE}/.ssh:/home/node/.ssh:ro
      - ${HOME}${USERPROFILE}/.aws:/home/node/.aws
      - ${HOME}${USERPROFILE}/.git:/home/node/.git
    # プロセスが終了してコンテナが終了してしまわないように
    command: /bin/sh -c "while sleep 1000; do :; done"